info:
  contact: {}
paths:
  /greet:
    get:
      description: Get a simple greeting message
      operationId: get-greeting
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Get a greeting message
swagger: "2.0"
